name: Bump Version

on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * *"  # Runs daily at 12:00

jobs:
  check-version:
    runs-on: ubuntu-latest
    env:
      NOTIFY: false   # default
    permissions:
      issues: write   # must have write access to issues
    steps:
      - name: Set up Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

      # Checkout the NuOscillator repository
      - name: Checkout NuOscillator repository
        uses: actions/checkout@v5
        with:
          repository: dbarrow257/NuOscillator
          path: NuOscillator
          fetch-depth: 0

      # Extract the NuOscillator version from CMakeLists.txt
      - name: Get NuOscillator version
        run: |
          NuOscillator_version=$(grep -Po '(?<=set\(NUOSCILLATOR_VERSION )\d+\.\d+\.\d+' NuOscillator/CMakeLists.txt)
          echo "Extracted NuOscillator version: ${NuOscillator_version}"
          echo "NUOSCILLATOR_VERSION=${NuOscillator_version}" >> $GITHUB_ENV

      # Get the latest tag in NuOscillator
      - name: Get NuOscillator tag version
        run: |
          cd NuOscillator
          git fetch --tags
          NuOscillator_tag_version=$(git describe --tags $(git rev-list --tags --max-count=1))
          NuOscillator_tag_version=${NuOscillator_tag_version#v}   # remove leading v if present
          echo "Extracted NuOscillator tag version: ${NuOscillator_tag_version}"
          echo "NUOSCILLATOR_TAG_VERSION=${NuOscillator_tag_version}" >> $GITHUB_ENV

      # Compare versions and set NOTIFY=true if they match
      - name: Compare versions
        run: |
          if [ "${{ env.NUOSCILLATOR_VERSION }}" = "${{ env.NUOSCILLATOR_TAG_VERSION }}" ]; then
            echo "Versions match!"
            echo "NOTIFY=false" >> $GITHUB_ENV
          else
            echo "Versions do not match."
            echo "NOTIFY=true" >> $GITHUB_ENV
          fi

      # Notify users by creating a comment with version info
      - name: Comment on issue #154
        if: env.NOTIFY == 'true'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const version = process.env.NUOSCILLATOR_VERSION;
            const tag = process.env.NUOSCILLATOR_TAG_VERSION;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: 154,
              body: `🎉 Automated comment: NuOscillator version \`${version}\` did not match the latest tag \`${tag}\`! 🚀\n\n@dbarrow257 and @kskwarczynski, please update me`
            })
