name: Bump Version

on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * *"  # Runs daily at 12:00
  push:
    branches:
      - feature/botSpam

jobs:
  check-version:
    runs-on: ubuntu-latest
    env:
      NOTIFY: false   # default
    steps:
      - name: Set up Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

      # Checkout the NuOscillator repository
      - name: Checkout NuOscillator repository
        uses: actions/checkout@v5
        with:
          repository: dbarrow257/NuOscillator
          path: NuOscillator
          fetch-depth: 0

      # Extract the NuOscillator version from CMakeLists.txt
      - name: Get NuOscillator version
        run: |
          NuOscillator_version=$(grep -Po '(?<=set\(NUOSCILLATOR_VERSION )\d+\.\d+\.\d+' NuOscillator/CMakeLists.txt)
          echo "Extracted NuOscillator version: ${NuOscillator_version}"
          echo "NUOSCILLATOR_VERSION=${NuOscillator_version}" >> $GITHUB_ENV

      # Get the latest tag in NuOscillator
      - name: Get NuOscillator tag version
        run: |
          cd NuOscillator
          git fetch --tags
          NuOscillator_tag_version=$(git describe --tags $(git rev-list --tags --max-count=1))
          NuOscillator_tag_version=${NuOscillator_tag_version#v}   # remove leading v if present
          echo "Extracted NuOscillator tag version: ${NuOscillator_tag_version}"
          echo "NUOSCILLATOR_TAG_VERSION=${NuOscillator_tag_version}" >> $GITHUB_ENV

      # Notify users if versions match
      - name: Notify users
        if: env.NOTIFY == 'true'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.issues.create({
              ...context.repo,
              title: "🎉 NuOscillator Version Match",
              body: "Hey @kskwarczynski and @dbarrow257 — the NuOscillator version in `CMakeLists.txt` **matches** the latest Git tag (`${{ env.NUOSCILLATOR_VERSION }}`). Big pog! 🚀",
              assignees: ["kskwarczynski", "dbarrow257"]
            })
