# Update NuOscillator container image registry with newest updates
name: Image CD

# The events that trigger the workflow
on:
  push:
    branches: [ main ]
  release:
    types: [ published ]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false  # KS: Prevents cancellation of remaining jobs if one fails
      matrix:
        include:
          - os: alma9
            file: Docs/DockerFiles/Alma9/Dockerfile
            tag_latest: alma9latest
            cmakeoptions: -DUseDoubles=1 -DUseMultithreading=1 -DUseCUDAProb3=1 -DUseCUDAProb3Linear=1 -DUseProb3ppLinear=1 -DUseNuFASTLinear=1 -DUseProbGPULinear=0 -DUseOscProb=1 -DUseNuSQUIDSLinear=1 -DUseGLoBESLinear=1


    name: Image CD ${{ matrix.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build Docker image
      run: |
        if [ "${{ github.event_name }}" == 'release' ]; then
          docker build . --file ${{ matrix.file }} --tag ghcr.io/${{ github.repository_owner }}/nuoscillator:${{ matrix.os }}${{ github.event.release.tag_name }} --build-arg NUOSCILLATOR_VERSION=main --build-arg CMAKE_OPTIONS="${{ matrix.cmakeoptions }}"
        else
          docker build . --file ${{ matrix.file }} --tag ghcr.io/${{ github.repository_owner }}/nuoscillator:${{ matrix.tag_latest }} --build-arg NUOSCILLATOR_VERSION=main --build-arg CMAKE_OPTIONS="${{ matrix.cmakeoptions }}"
        fi

    - name: Push Docker image
      run: |
        if [ "${{ github.event_name }}" == 'release' ]; then
          docker push ghcr.io/${{ github.repository_owner }}/nuoscillator:${{ matrix.os }}${{ github.event.release.tag_name }}
        else
          docker push ghcr.io/${{ github.repository_owner }}/nuoscillator:${{ matrix.tag_latest }}
        fi

    - name: Delete old images
      uses: actions/delete-package-versions@v5
      with:
        package-name: 'nuoscillator'
        package-type: 'container'
        min-versions-to-keep: 5
        delete-only-untagged-versions: 'true'
